// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _3_DataAccessLayerClinics.Models;

public partial class Booking
{
    public int ID { get; set; }

    public DateOnly BookingDate { get; set; }

    public TimeOnly BookingTime { get; set; }

    public bool IsPaid { get; set; }

    public decimal? DetectionCost { get; set; }

    public int? PatientID { get; set; }

    public int? DoctorID { get; set; }

    public int? CreatedByNurseID { get; set; }

    public DateOnly CreatedAt { get; set; }

    public virtual Nurse CreatedByNurse { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}