// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _3_DataAccessLayerClinics.Models;

public partial class Doctor
{
    public int ID { get; set; }

    public string FirstName { get; set; }

    public string SecondName { get; set; }

    public string ThirdName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public int? Age { get; set; }

    public string Gender { get; set; }

    public int? Salary { get; set; }

    public string Username { get; set; }

    public string password { get; set; }

    public string Salt { get; set; }

    public int? SpecialtyID { get; set; }

    public int? NurseID { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual Nurse Nurse { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<ScheduleDoctorMapping> ScheduleDoctorMappings { get; set; } = new List<ScheduleDoctorMapping>();

    public virtual Specialty Specialty { get; set; }
}