// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _3_DataAccessLayerClinics.Models;

public partial class DoctorSchedule
{
    public int ID { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }
    public string DayOfWeek { get; set; }

    public virtual ICollection<ScheduleDoctorMapping> ScheduleDoctorMappings { get; set; } = new List<ScheduleDoctorMapping>();
}