// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _3_DataAccessLayerClinics.Models;

public partial class Payment
{
    public int ID { get; set; }

    public int? BookingID { get; set; }

    public decimal? DetectionCost { get; set; }

    public string PaymentMethod { get; set; }
    public string? phoneNumberpaymentTo { get; set; }

    public bool? IsCash { get; set; }


    public virtual Booking Booking { get; set; }
}